name: Deploy to S3
on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Discord notification on success
      - name: Discord notification (Success)
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ✅ **Deployment Successful!** 🚀
            
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** [${{ github.sha }}] (https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            **Author:** ${{ github.actor }}
            **Message:** 
            ```
            ${{ github.event.head_commit.message }}
            ```
      
      # Discord notification on failure
      - name: Discord notification (Failure)
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ❌ **Deployment Failed!** 💥
            
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** [${{ github.sha }}] (https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            **Author:** ${{ github.actor }}
            **Message:** 
            ```
            ${{ github.event.head_commit.message }}
            ```
   
